### PR TITLE
Added option to loop fixed number of times

### PR DESCRIPTION
**Pull request by megascope**
Allow `--loop` to take an integer value to specify the number of loops, or -1 for infinite looping.

### CODE REVIEW

**Comment by fieldOfView** [comment]
Cool!

My only problem with this PR is that - from the looks of it - just specifying `--loop` as before no longer works; you need to specify `--loop -1` to get the same result.

It has been a little while since I looked into argparser. Would it be possible to support the following:
`--loop` -> loops indefinitely
`--loop 2` -> loops exactly twice
no loop argument added -> does not loop

**Comment by fieldOfView** [comment]
Should be possible with `.add_argument('--loop', nargs='?', type=int, const=None,
                       help='Loop indefinitely (--loop) or n times (--loop n)')`

**Comment by megascope** [comment]
Resolved

**Comment by fieldOfView** [comment]
Awesome, thanks!

**Pull request merged**
